### PR TITLE
The New Beginnings

### PR DESCRIPTION
**Pull request by chriddyp**
This is a first pass at our new way for creating Dash components: fork the repo, find-and-replace a bunch of stuff, and you're off to the races.

Once we merge this, we will deprecate `dash-components-archetype` and use this repo instead.

@plotly/dash Please review! This is part of our shared code that we will all have a shared responsibility in maintaining and supporting.

### CODE REVIEW

**Comment by chriddyp** [comment]
Some quick thoughts on why I think this is a pretty decent solution as compared to the previous archetype or a different CLI tool that we might build. Many thanks to @bpostlethwaite for helping me come around:
- It's easier to update one's component with changes that we make in this repo, it's just `git merge`
- `git clone` is a really familar workflow
- In the archetype, the actual code was nested under an `init` folder which made it pretty hard to just inspect the code and understand what's going on
- Right now, there is some manual copy-and-paste required, but in the future we can replace that with some `init` CLI that does it for you

**Comment by xhlulu** [comment]
What should we do if we want to create a private component using this boilerplate? Should we download it as a ZIP and create a new repo?

**Comment by chriddyp** [comment]
> Should we download it as a ZIP and create a new repo?

Yup that works. Or just `git clone` and then change the remotes to your private repo.

**Comment by bpostlethwaite** [comment]
If anyone is feeling adventurous they could write a little script in the root of this repo that copies all the files in the repo (aside from the script itself) into directory {app name} and templates {app name} into the correct places for extra points :)

The script could ask the user for an App name.

The script would need to be able to be run on windows. Probably node.js but I suppose it could be python!

**Comment by T4rk1n** [comment]
@rmarren1 How do you generate the class files for the IDE support ? Should it be available in a script ?

**Comment by T4rk1n** [comment]
So I was inspired (bored) this weekend and I made a cli to help with the development of dash components. Made with python argparse.

requirements:

- git

Repo:

https://github.com/plotly/dash-cli

Still a work in progress but basic functionality is there.

`dash --help` for full help.

**Initialize a new components lib from the boilerplate.**

`dash component-boilerplate my_components`

- git clone the boilerplate in the current dir.
- rename the component directory to my_components.
- change package.json name, description, etc.
- change MANIFEST.in

```
(venv) C:\Users\t4rk\dev\dash-cli-test>dash component-boilerplate test_component
Author: tark
Author email: t4rk@outlook.com
Description: Hello world
```

```
(venv) C:\Users\t4rk\dev\dash-cli-test>dash component-boilerplate --help
usage: dash component-boilerplate [-h] [-a AUTHOR] [-m AUTHOR_EMAIL]
                                      [-d DESCRIPTION] [-l LICENSE]
                                      [-b BOILERPLATE]
                                      name

positional arguments:
  name                  The name of the components lib.

optional arguments:
  -h, --help            show this help message and exit
  -a AUTHOR, --author AUTHOR
                        asked
  -m AUTHOR_EMAIL, --author-email AUTHOR_EMAIL
                        asked
  -d DESCRIPTION, --description DESCRIPTION
                        asked
  -l LICENSE, --license LICENSE
                        The license of the repo.
  -b BOILERPLATE, --boilerplate BOILERPLATE
                        override the default boilerplate cloned.
```

**Generate a component**

`dash generate-components test_component lib/metadata.json` generate class components as file.

There is watch option with `--watch`.

Later on we could add more commands.

**Comment by chriddyp** [comment]
🎉 Very nice! Seems like a decent architecture: the `cli` that clones this repo.

For this particular repo, @plotly/dash can we 💃 ? I'd like to merge this in and update the official plugin docs if we are all in agreement.

Then, we could update the docs afterwards with @T4rk1n 's CLI once a few of us test it. We could provide the "fork and find-and-replace" option as an alternative to the CLI.

**Comment by bpostlethwaite** [comment]
Heck yes! :dancer:

**Comment by rmarren1** [comment]
You should be able to generate python classes using [this command](https://github.com/plotly/dash-components-archetype/blob/82197e3e76139457aebf462cea86ef4d64bb4b2b/init/package.json#L17)

**Pull request merged**
