### PR TITLE
Minor updates to the README.md

### PR DESCRIPTION
**Pull request by xhlulu**
See screenshot below.

Changes:
- Use hyperlinks instead of raw links
- Moved important links to the top
- Added a few new links (dash-cytoscape, dash-deck, etc.)
- Changed the cookiecutter instructions from the full URL to `gh:plotly/dash-component-boilerplate`

### CODE REVIEW

**Comment by xhlulu** [comment]
New look: 

image

Old look:

image

**Comment by xhlulu** [comment]
New Look:
image


Old look:
image

**Review by alexcjohnson — APPROVED** [review]
💃 Nice updates!

**Comment by alexcjohnson** [comment]
Hmm unclear to me how the Py3.7 test managed to succeed, nor how to get around the Py3.6 failure until https://github.com/hackebrot/pytest-cookies/issues/51 is solved.

**Comment by xhlulu** [comment]
@alexcjohnson py3.6 errors seem to be related to the cryptography one; would pinning to 3.3 solve it? Anyway, I made [an issue](https://github.com/plotly/dash-component-boilerplate/issues/120) to track that.

**Pull request merged**
