### PR TITLE
Allow numbers in project_shortname

### PR DESCRIPTION
**Pull request by LiamConnors**

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Yes, definitely a good change! I don't know why the test failed, doesn't look related at all to your change but it would be good to figure out what's going on.

**Comment by LiamConnors** [comment]
Investigating the 3.6 failure. The 2.7 failure I understand as `fullmatch` won't be available there. Is 2.7 something we would still need to support?

**Comment by alexcjohnson** [comment]
Yep, You can drop Py2. 🔪

**Comment by LiamConnors** [comment]
Thanks @alexcjohnson. I removed the Python 2.7 tests. I updated the 3.6 test. It was checking in the `/src` directory for one of the .jl files but when I ran this locally that file is in `/src/jl`
https://github.com/plotly/dash-component-boilerplate/pull/144/files#diff-2cbedc61dab388ecb7f41cb83ec124ab9c1e9f297fe7ee2d548df29b3a6bb2bbR62
Updating the test resolved the test failure but I'm not 100% sure what the correct behaviour is there

**Review by alexcjohnson — APPROVED** [review]
Oh right, the component generator has changed to use `src/*.jl`

Nice work! 💃

**Pull request merged**
